// <auto-generated />
using API_CRUD_Project.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_CRUD_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210125095751_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("API_CRUD_Project.Models.Boxer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boxers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "King In the Ring",
                            Division = "Heavyweight",
                            FullName = "Muhammed Ali",
                            Status = "Retired"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Iron",
                            Division = "Heavyweight",
                            FullName = "Mike Tyson",
                            Status = "Retired"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Lioness",
                            Division = "Heavyweight",
                            FullName = "Lenox Lewis",
                            Status = "Retired"
                        },
                        new
                        {
                            Id = 4,
                            Alias = "Real Deal",
                            Division = "Heavyweight",
                            FullName = "Evander Holyfiled",
                            Status = "Retired"
                        },
                        new
                        {
                            Id = 5,
                            Alias = "Savage",
                            Division = "Heavyweight",
                            FullName = "Rock Marciano",
                            Status = "Retired"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
